---
name: docker-base-node
blueprint:
  name: docker/image

## Overrides Hammer Global Config
main_user:
  name: Marcelo Correia
  description: Marcelo Correia
  github_user: marcelocorreia
  linkedin: https://www.linkedin.com/in/marcelocorreia
  docker_hub_user: marcelocorreia
  ansible_galaxy_user: marcelocorreia
  website: https://marcelo.correia.io
  email: marcelo@correia.io
  slack: https://correia-group.slack.com

tags:
  - terraform
  - module
  - aws
  - enc

readme:
  overview: |
    Docker NodeJS Base image

  dockerfiles:
    - Dockerfile

  usage: |
    ```bash
    $ docker run --rm marcelocorreia/base-node node -v

    ```
    ## Setting timezone
    ```bash
    $ docker run --rm -e TZ=Australia/Sydney marcelocorreia/base-node node -v
    ```
    ### Extending
    ```Dockerfile
    FROM marcelocorreia/base-node
    ...
    ```
    **Targets**
    ```bash
    $ make release
    $ make build
    $ make push
    $ make all-versions
    $ make current-version
    $ make next-version
    ```

  shields:
    - https://img.shields.io/docker/pulls/marcelocorreia/base-node.svg
    - https://img.shields.io/github/languages/top/marcelocorreia/docker-base-node.svg
    - https://api.travis-ci.org/marcelocorreia/docker-base-node.svg?branch=master
    - https://img.shields.io/github/release/marcelocorreia/docker-base-node.svg?flat-square

  tldr:
    - '[Overview](#overview)'
    - '[Description](#description)'
    - '[Dockerfile](#dockerfile)'
    - '[Usage](#usage)'
    - '[License](#license)'
    - '**Semver versioning**'

  licenses:
    - apache-license